# Generated by Django 3.2.7 on 2021-10-03 13:05

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=images.models.image_directory_path)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
